apiVersion: intersystems.com/v1alpha1
kind: IrisCluster
metadata:
  name: iris
spec:
  # Empty license in our case
  licenseKeySecret:
    name: iris-license

  # Custom IRIS configuration
  configSource:
    name: common.cpf

  # Topology section defines an architecture
  # It doesn't contain "shards" field, so a standalone instance is deployed
  topology:
    data:
      image: containers.intersystems.com/intersystems/iris-community:2025.1
      podTemplate:
        spec:
          args:
          - --check-caps
          - "false"
          resources:
            requests:
              cpu: 300m
              memory: 1Gi
            limits:
              cpu: 300m
              memory: 1Gi
